---
 - name: ping
   ping:

 - name: Install nginx
   apt:
    name: nginx
    state: present
    update_cache: yes

 - name: nginx start
   service:
    name: nginx
    state: started
    enabled: yes

 - name: Clear web root
   file:
    path: /var/www/html/
    state: absent

 - name: recreate web root
   file:
    path: /var/www/html/
    state: directory
    mode: 0755

 - name: deploy website into nginx
   copy:
    src: website/
    dest: /var/www/html/
    mode: 0644
   
   notify: restart nginx    